### PR TITLE
fix: font size format issue

### PR DESCRIPTION
**Pull request by Jennievon**
# :books: Linear Ticket :books:

#LIQ-132

### CODE REVIEW

**Review by bradleySuira — APPROVED** [review]
Looks great!

**Comment by Jennievon** [comment]
@bradleySuira I can't seem to be able to merge.

**Comment by bradleySuira** [comment]
> 

not sure why @Jennievon , maybe it's about permissions we can ask to @monokh that has admin permissions

**Comment by Jennievon** [comment]
It worked in the last PR, wonder what happened again.

**Pull request merged**
