### PR TITLE
feat: addd priv-key-precommit

### PR DESCRIPTION
**Pull request by beemi**
# :books: Linear Ticket :books:

### CODE REVIEW

**Review by kraikov — APPROVED** [review]

**Comment by kraikov** [comment]
can we lock the version?

**Comment by kraikov** [comment]
can we lock the version?

**Review by kraikov — CHANGES_REQUESTED** [review]
can we lock the version?

**Comment by beemi** [comment]
> can we lock the version?

its done

**Review by kraikov — APPROVED** [review]

**Pull request merged**
