### PR TITLE
fix: store custom token decimals in number format instead of a string

### PR DESCRIPTION
**Pull request by skeremidchiev**
# :books: Linear Ticket :books:

[LIQ-861](https://linear.app/liquality/issue/LIQ-861/custom-tokens-decimals-are-stored-as-string-instead-of-number)

### CODE REVIEW

**Review by AndonMitev — APPROVED** [review]
LGTM

**Review by monokh — APPROVED** [review]
LGTM, might be better to be a number before reaching the action

**Review by bradleySuira — APPROVED** [review]
LGTM

**Comment by skeremidchiev** [comment]
I have found few more bugs related to the custom tokens. I will close this PR and reopen a new one.

**Pull request closed without merging**
